#!/bin/bash
#SBATCH --job-name=test_A
#SBATCH --partition=cpu_il
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=64
#SBATCH --time=09:00:00
#SBATCH --mem-per-cpu=2000mb
#SBATCH --output=job_%j.out
#SBATCH --error=job_%j.err

set -euo pipefail

cd $HOME/FastFortranBoltzmann
source .venv/bin/activate

# domain decomposition
IMAGES=$SLURM_NTASKS
I_X=8
I_Y=8

# compile-time setting overwrites
FFB_SETTINGS_DEFINITIONS=(
    FFB_USE_CMAKE_SETTINGS
    FFB_SIM_MODE=4
    FFB_N_X=5040
    FFB_N_Y=5040
    FFB_N_STEPS=3000000
    FFB_USE_UNROLLED_KERNELS=.true.
    FFB_USE_UNIVERSAL_KERNELS=.true.
    FFB_USE_SINGLE_SYNC_EXCHANGE=.false.
    FFB_EXPORT_RHO=.false.
    FFB_EXPORT_U_X=.true.
    FFB_EXPORT_U_Y=.true.
    FFB_EXPORT_U_MAG=.true.
    FFB_EXPORT_INTERVAL=100000
    FFB_EXPORT_INITIAL_STATE=.true.
    FFB_EXPORT_FINAL_STATE=.true.
    FFB_INTERACTIVE_PROGRESS=.true.
    FFB_PROGRESS_INTERVAL=1
    FFB_RHO_0=1.0_FP
    FFB_OMEGA=1.5_FP
    FFB_U_MAX=0.1_FP
    FFB_N_SIN=2.0_FP
    FFB_U_WALL=0.1_FP
    FFB_U_LID=0.1_FP
    FFB_RHO_IN=1.001_FP
    FFB_RHO_OUT=0.999_FP
)
FFB_SETTINGS_DEFINITIONS=$(IFS=';'; echo "${FFB_SETTINGS_DEFINITIONS[*]}")

# load modules
module purge
module load compiler/intel
module load mpi/impi

# create job-specific build
export BUILD_DIR=$PWD/build/release-native-$SLURM_JOB_ID
cmake -S . -B "$BUILD_DIR" -G Ninja \
    -DCMAKE_Fortran_COMPILER=ifx \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_Fortran_FLAGS= \
    -DCMAKE_Fortran_FLAGS_RELEASE="-O3 -march=native" \
    -DFFB_EXPORT_NUM="run_${SLURM_JOB_ID}" \
    -DFFB_SETTINGS_DEFINITIONS="$FFB_SETTINGS_DEFINITIONS"
cmake --build "$BUILD_DIR"

# print metadata
echo "ID/NAME:    $SLURM_JOB_ID / $SLURM_JOB_NAME"
echo "USER:       $SLURM_JOB_USER"
echo "PARTITION:  $SLURM_JOB_PARTITION"
echo "TASKS:      $SLURM_TASKS_PER_NODE tasks/node x $SLURM_JOB_NUM_NODES nodes = $SLURM_NTASKS tasks"
echo "NODES:      $SLURM_JOB_NODELIST"
echo "COMPILER:"
ifx --version
echo "MPI:"
mpirun --version

# generate config file and run
export FOR_COARRAY_CONFIG_FILE=$HOME/FastFortranBoltzmann/${SLURM_JOB_ID}.conf
export EXE=$BUILD_DIR/bin/FFB
unset I_MPI_PIN_PROCESSOR_LIST
printf '%s\n' "-genvall -genv FOR_ICAF_STATUS launched -genv I_MPI_FABRICS=shm:ofi -genv I_MPI_PIN=1 -genv I_MPI_PIN_DOMAIN=core -genv I_MPI_PIN_ORDER=scatter -genv I_X=$I_X -genv I_Y=$I_Y -n $IMAGES $EXE" > "$FOR_COARRAY_CONFIG_FILE"

# python3 -u scripts/benchmark_runs.py --exe $EXE --runs 3 --images $IMAGES --ix $I_X --iy $I_Y
"$EXE"
